---
language: python
python: '2.7'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true
  matrix:
    # Spin off separate builds for each of the following versions of Ansible
    - MOLECULEW_ANSIBLE=2.7.15
    - MOLECULEW_ANSIBLE=2.9.1

# Require Ubuntu 16.04
dist: xenial

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
